# Makefile for the AW_Lib
#
# @author Marcelo Coraça de Freitas <marcelo.batera@gmail.com> 

VERSION=3.0

ifndef ($(PREFIX))
	PREFIX=/usr/local
endif
INCLUDE_PREFIX=$(PREFIX)/include
LIB_PREFIX=$(PREFIX)/lib
GPR_PREFIX=$(LIB_PREFIX)/gnat


projectFile="apq-ct_lib.gpr"

#OUTPUT_NAME is the name of the compiled library.
ifeq ($(OS), Windows_NT)
	OUTPUT_NAME=apq-ct_libhelp.dll
else
	OUTPUT_NAME=libapq-ct_libhelp.so
endif




libs: c_libs
	gnatmake -P ${projectFile}



c_objs:
	make -C src-c/

c_objs-clean:
	make -C src-c/ clean



apq-ct_lib.ads:
	make -C extras

apq-ct_lib.ads-clean:
	make -C extras clean
	rm -f src/apq-ct_lib.ads


c_libs: apq-ct_lib.ads c_objs
	cd lib && gcc -shared  ../obj-c/c_ct_lib.o -o $(OUTPUT_NAME)  -lct

#c_objs:
#	cd obj-c && gcc -I../src-c ../src-c/numeric.c -c -o numeric.o && gcc -I../src-c ../src-c/notices.c -c -o notices.o

all: libs 


clean: apq-ct_lib.ads-clean c_objs-clean 
	@rm -f obj-c/* lib/*
	gnatclean -P ${projectFile}
	@echo "All clean"

docs:
	@-./gendoc.sh
	@echo "The documentation is generated by a bash script. Then it might fail in other platforms"


gprfile:
	@echo "Preparing GPR file.."
	@echo version:=\"$(VERSION)\" > gpr/apq.def
	@echo prefix:=\"$(PREFIX)\" >> gpr/apq.def
	@gnatprep gpr/apq-ct_lib.gpr.in gpr/apq-ct_lib.gpr gpr/apq.def
	@gnatprep gpr/apq-ct_lib_c.gpr.in gpr/apq-ct_lib_c.gpr gpr/apq.def

gprclean:
	@rm -f gpr/*gpr
	@rm -f gpr/*.def


install: gprfile
	@echo "Installing files"
	install -d $(INCLUDE_PREFIX)
	install -d $(LIB_PREFIX)
	install -d $(GPR_PREFIX)
	install src*/*.* -t $(INCLUDE_PREFIX)
	install lib/* -t $(LIB_PREFIX)
	install gpr/*.gpr -t $(GPR_PREFIX)
	make gprclean
